# Generated by Django 4.1.5 on 2024-01-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_featured_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='featured_plans',
        ),
        migrations.AlterField(
            model_name='plans',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_plans', to='projects.projects'),
        ),
    ]
