# Generated by Django 4.1.5 on 2024-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_app_name', models.CharField(default='Cpm_Diagram_Maker', max_length=150)),
                ('project_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
                ('nodes_ondemand_id', models.IntegerField(default=0)),
                ('edges_ondemand_id', models.IntegerField(default=0)),
            ],
        ),
    ]
