# Generated by Django 4.1.5 on 2024-01-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='edges_ondemand_id',
            new_name='edge_ondemand_id',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='nodes_ondemand_id',
            new_name='node_ondemand_id',
        ),
    ]
