# Generated by Django 4.1.5 on 2024-01-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_plans_owner_user_projects_owner_user'),
        ('core', '0002_rename_edges_ondemand_id_generalinfo_edge_ondemand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='plan_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.plans'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='project_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
