# Generated by Django 4.1.5 on 2024-01-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalinfo_plan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='project_id',
            new_name='project',
        ),
    ]
