# Generated by Django 4.1.5 on 2024-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
