# Generated by Django 4.1.5 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('En', 'English'), ('Es', 'Spanish'), ('Fr', 'French')], default='En', max_length=3),
        ),
    ]
