# Generated by Django 4.1.5 on 2024-02-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profileimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImages',
            new_name='ProfileImage',
        ),
    ]
