# Generated by Django 4.1.5 on 2024-01-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_alter_plans_date_created_alter_projects_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.IntegerField(choices=[(0, 'Activity'), (1, 'Milestone'), (2, 'Risk'), (3, 'Note')], default=0)),
                ('node_name', models.CharField(default='Activity', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RiskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(blank=True, default='cpm_risk', max_length=150)),
                ('risk_note', models.TextField(blank=True, default='', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
            ],
        ),
        migrations.CreateModel(
            name='NoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_value', models.TextField(blank=True, default='', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
            ],
        ),
        migrations.CreateModel(
            name='NodesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_position', models.JSONField(blank=True, default=dict)),
                ('node_data', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='elements.nodetypes')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(blank=True, default='cpm_milestone', max_length=150)),
                ('milestone_type', models.CharField(choices=[('H', 'Hard'), ('NLT', 'No Later Than')], default='H', max_length=3)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('milestone_note', models.TextField(blank=True, default='', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
            ],
        ),
        migrations.CreateModel(
            name='EdgesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.IntegerField()),
                ('edge_target', models.IntegerField()),
                ('edge_lag', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(blank=True, default='cpm_activity', max_length=150)),
                ('activity_startdate', models.DateField(blank=True, null=True)),
                ('activity_enddate', models.DateField(blank=True, null=True)),
                ('activity_duration_type', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month')], default='D', max_length=1)),
                ('activity_p10', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_base', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_p90', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_note_low', models.TextField(blank=True, default='', null=True)),
                ('activity_note_base', models.TextField(blank=True, default='', null=True)),
                ('activity_note_high', models.TextField(blank=True, default='', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plans')),
            ],
        ),
    ]
