# Generated by Django 4.1.5 on 2024-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetypes',
            name='node_name',
            field=models.CharField(default='name', max_length=150),
        ),
    ]
